name: irispy

channels:
    - conda-forge

dependencies:
    - python=3
    - sphinx
    - astropy
    - matplotlib
    - numpy
    - sunpy

- pip:
    - git+https://github.com/sunpy/sunpy-sphinx-theme.git@v0.1.0a3
