name: irispy

channels:
    - conda-forge

dependencies:
    - python=3
    - sphinx
    - astropy
    - matplotlib
    - numpy
    - sunpy>=0.8.0rc1
    - pip:
      - sunpy-sphinx-theme
      - git+https://github.com/sunpy/ndcube
